### PR TITLE
Tests for refactored station module

### PR DESCRIPTION
**Pull request by SuhasHebbar**

### CODE REVIEW

**Comment by prasadtalasila** [comment]
@SuhasHebbar The coveralls report is not being pushed through. Also the credo code quality tool needs to run on all the elixir files.

**Comment by prasadtalasila** [comment]
issues to fix:

1. Update mox dependency to 0.3
2. Remove the credo issues / errors reported in travis build log
3. Include queryID of type string in all queries used in tests
    1. Please update the [proposed architecture](https://github.com/prasadtalasila/TransportScheduler/wiki/Proposed-Architecture-for-TS-v1.0-alpha) and [station tests](https://github.com/prasadtalasila/TransportScheduler/wiki/Station-Tests-for-TS-v1.0-alpha)

**Comment by prasadtalasila** [comment]
@VedangW We are back to square here again, aren't we? Suhas had a single commit after rebasing leading to PR and it was forcibly changed to 20 commits with out rebase.

Please revert the changes and have one commit leading to this PR.

**Comment by VedangW** [comment]
Sir, I made that commit by mistake. I'll take care of it.

**Comment by prasadtalasila** [comment]
@SuhasHebbar @VedangW Please fix the errors given by credo and push another commit. Are there any other pending improvements related to this PR?

**Comment by VedangW** [comment]
Sir,

We'll make the commit. And there are no other changes that we discussed the
other day.

**Pull request merged**
