### PR TITLE
Station FSM and Genserver

### PR DESCRIPTION
**Pull request by prasadtalasila**
Station FSM and Genserver

### CODE REVIEW

**Comment by prasadtalasila** [comment]
@VedangW Good that code coverage has improved to 72%. It needs to be 90+% for this PR to be accepted. There are a lot of credo errors shown in the travis build log. Please rectify them as well.

**Comment by VedangW** [comment]
@prasadtalasila Sir I'm picking up this PR again now that compre is over.

**Comment by prasadtalasila** [comment]
@VedangW any updates on the PR?

**Comment by VedangW** [comment]
Sir I have been trying to get the send_to_neighbour() function to work.
That would solve most of the problems, but I haven't been able to
understand how to integrate the pid functionality with the fsm.

**Comment by prasadtalasila** [comment]
Once the pids of neighbours are known, it should be straight forward to send to the neighbours right? Am I missing anything?

Please post the offending code as a GitHub gist and post a link. Perhaps @SuhasHebbar can help.

**Comment by VedangW** [comment]
@SuhasHebbar  this is the problem I am facing currently:

send_to_neighbour():
```elixir
       def send_to_neighbour(conn, itinerary, registry) do
		# send itinerary to
		registry.lookup_code(conn[:dst_station])
		# next_station.query_input(itinerary)
		# Station.send_to_stn(next_station_pid, itinerary)
	end
```
this is the way it needs to be implemented. Considering that our station is the station which is sending the updated to the next station, I am not sure how the pid of the receiving station comes into picture. Do we need to retrieve the FSM of the receiving station using the pid and send it from the FSM of our current station? Also, as I understand it, when we look at the GenServer, we look at it from a module point of view. In this point of view, this functionality should typically be implemented as two functions, ```send_to_stn``` and ```receive_at_stn```, but we only have one function. Can someone please explain how this function exactly works?

**Comment by prasadtalasila** [comment]
@VedangW The function needs to send the itinerary to its neighbour. The pid of the neighbour is not known; hence, the pid needs to be looked up from the registry. Once the pid is known, the itinerary message is sent from the current station to the next.

To be clear, only two FSMs are active in each station. One FSM is the station FSM that processes the queries. The second FSM is activated in prefCheck(conn,itinerary) function. I understand that the prefCheck() function would be initially empty. So, at the moment, we are talking of only one FSM, the station FSM.

**Comment by VedangW** [comment]
@prasadtalasila Sir I haven't put in two of the station GenServer functions (```receive_at_src``` and ```send_to_station```) and their corresponding tests since I have been getting some errors in the tests. I have written the complete code for station (the GenServer interface) and will put it in as soon as the tests run. Apart from that I have added appropriate tests for the station_functions. 

I have a doubt here - the tests for StationFSM already include these tests:
- Check status of query with self-loop in 'query_rcvd' state
- Check status of query with wrong dst in 'query_rcvd' state
- Send completed query to station in 'query_rcvd' state
which closely resemble the tests we initially wrote for Station. These now pass for StationFSM. Do they still need to be there for Station?

**Comment by prasadtalasila** [comment]
@VedangW I understand your question as follows.

* There are station tests written a long-time ago that actually check some of the work done in states such as `query_rcvd`. These tests are now passing.    
    **Observation:** This is good and is expected behavior.
* Do the tests still need to be there?    
    **Observation:** This part I did not understand. We have tests for the station with out concerning ourselves with the actual implementation details (whether we implement the station using FSM or not). If these tests pass and provide the required coverage, then good. Otherwise, we need to add more tests.

**Comment by VedangW** [comment]
@SuhasHebbar getting this error on using Mox even though you had already defined the expectations:
```bash
1) test Receive a itinerary search query (StationTest)
     test/ts/station_test.exs:91
     ** (EXIT from #PID<0.238.0>) an exception was raised:
         ** (Mox.UnexpectedCallError) no expectation defined for MockRegister.check_active/1 in process #PID<0.239.0>
             (mox) lib/mox.ex:438: Mox.__dispatch__/4
             (TransportScheduler) lib/ts/station_fsm.ex:26: StationFsm.query_status/3
             (TransportScheduler) lib/ts/station_fsm.ex:214: StationFsm.transition/3
             (TransportScheduler) lib/ts/station.ex:83: Station.handle_cast/2
             (stdlib) gen_server.erl:601: :gen_server.try_dispatch/4
             (stdlib) gen_server.erl:667: :gen_server.handle_msg/5
             (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3

....

Finished in 0.1 seconds
19 tests, 1 failure
```
Here are the expectations:
```elixir
                MockRegister
		|> expect(:check_active,
			fn(_) -> send(test_proc, :query_received)
			false
			end)
		|> expect(:lookup_code, fn(_) -> neighbour end)

		MockCollector
		|> expect(:collect, fn(_) -> true end)
```

**Comment by SuhasHebbar** [comment]
expect defines a function call expectation for one call. If the check_active function is called twice then for the second call no expectation has been defined.

Try

```elixir
stub(:check_active, fn(_) -> send(test_proc, :query_received) false end)
```

or
```elixir
expect(:check_active, 2, fn(_) -> send(test_proc, :query_received) false end)
```

**Comment by VedangW** [comment]
@SuhasHebbar that doesn't seem to be the problem. I used stub everywhere and it didn't work anyway.

**Comment by prasadtalasila** [comment]
PR #69 contains a correct implementation of the functionality discussed in this PR. Closing now.

**Pull request closed without merging**
