### PR TITLE
Station FSM and GenServer

### PR DESCRIPTION
**Pull request by VedangW**
Station GenServer receiving and storing state.

### CODE REVIEW

**Comment by prasadtalasila** [comment]
@VedangW I have a few concerns.
1. We committed the unit tests upfront and writing the minimum code to pass those tests. Because we are doing that, we necessarily should end up with 90%+ code coverage, not the 13% as reported by code coverage tool.
2. This PR seems to have all of the station code written recently. Ideally, it should have only code that passes the unit tests. @SuhasHebbar can have a branch in his repository containing the latest code written for station module. As we discussed in the morning meeting, only the code that is passing the tests shall be in the PR.

**Comment by VedangW** [comment]
Of course. I'll take care of it and send the revised PR.

**Comment by prasadtalasila** [comment]
@VedangW you need to modify the code to remove all the errors by credo. You can check the [build logs](https://travis-ci.org/prasadtalasila/TransportScheduler/builds/311712049) for all the errors.

Given that code coverage is not increasing, you might need to update the tests to make the code coverage 90%+.

**Comment by VedangW** [comment]
@prasadtalasila I was actually trying not to change the tests as I thought it might not have been good practice. Coveralls helps figure out which portion of the code is not covered by the tests, so is it possible that the creating a separate station_fsm might be the problem since we have no tests for that?

**Comment by prasadtalasila** [comment]
@VedangW 
Low coverage only means that there are not enough tests. If there is a clear case of missing tests, as in the case of station_fsm.ex, I suggest that those tests be added. If it's a case of a function being tested, but not all paths of the function being covered, I suggest adding new test here as well.

Please take care of these two possilities and then make a non-conflicting push. After that, we can take a call on the modification of the existing tests.

**Comment by VedangW** [comment]
I'm working on it sir.

**Comment by VedangW** [comment]
Sir, I have added the station_fsm tests and changed the station_fsm accordingly. There were many small errors in the station_fsm which were hindering its working. As of now, the station_fsm works as we want it to. There are a couple of things missing though:

- The feasibility_check function doesn't take into account time constraints
- The pref_check, as earlier isn't implemented because we haven't incorporated the UQCFSM
- The send_to_neighbour function doesn't actually send the itinerary to the neighbour, only looks up the neighbour pid in the registry.

Implementing the interface for the station shouldn't take much effort after this. Please let me work on this until the station module is made.

**Comment by prasadtalasila** [comment]
Travis CI and Coveralls reports are missing. Closing this PR and opening a new one.

**Pull request closed without merging**
